import { Router } from "express";
import authRouter from "./auth.js";
import settingsRouter from "./settings.js";
import administrationRouter from "./administration.js";
import teachersRouter from "./teachers.js";
import certificatesRouter from "./certificates.js";
import newsRouter from "./news.js";
import galleryRouter from "./gallery.js";
import studentsRouter from "./students.js";
import admissionsRouter from "./admissions.js";
import admissionsRequirementsRouter from "./admissions-requirements.js";
import admissionsDatesRouter from "./admissions-dates.js";
import eventsRouter from "./events.js";
import faqRouter from "./faq.js";
import achievementsIntRouter from "./achievements-international.js";
import achievementsNatRouter from "./achievements-national.js";
import directionsRouter from "./directions.js";
import aboutRouter from "./about.js";
import contactRouter from "./contact.js";
import mediaRouter from "./media.js";
import uploadRouter from "./upload.js";
import dashboardRouter from "./dashboard.js";
import subjectResultsRouter from "./subject-results.js";
import englishCertsRouter from "./english-certs.js";
import timetableRouter from "./timetable.js";

const router = Router();

router.use(authRouter);
router.use("/dashboard", dashboardRouter);
router.use("/settings", settingsRouter);
router.use("/administration", administrationRouter);
router.use("/teachers", teachersRouter);
router.use("/certificates", certificatesRouter);
router.use("/news", newsRouter);
router.use("/gallery", galleryRouter);
router.use("/students", studentsRouter);
router.use("/admissions", admissionsRouter);
router.use("/admissions-requirements", admissionsRequirementsRouter);
router.use("/admissions-dates", admissionsDatesRouter);
router.use("/events", eventsRouter);
router.use("/faq", faqRouter);
router.use("/achievements-international", achievementsIntRouter);
router.use("/achievements-national", achievementsNatRouter);
router.use("/directions", directionsRouter);
router.use("/about", aboutRouter);
router.use("/contact", contactRouter);
router.use("/media", mediaRouter);
router.use("/upload", uploadRouter);
router.use("/subject-results", subjectResultsRouter);
router.use("/english-certs", englishCertsRouter);
router.use("/timetable", timetableRouter);

export default router;
